const mughal_text = {
    type: jsPsychSummarizeText,
    preamble: `Mughal Empire`,
    questions: [
      {prompt: `Zahir al-Din Muhammad Babur had always dreamed of founding a great empire. His father, the ruler of a small central Asian state named Fergana in what is now Uzbekistan, was a descendant of the famous conqueror Timur. His mother came from the family of the Mongol leader Chinggis Khan. In 1494, at the age of eleven, Babur became ruler of Fergana following his father&apos;s unexpected death, and he set himself the task of gaining control of all the lands that had once fallen to his illustrious ancestor Timur. In 1504, he made a bold move. Striking out across the Hindu Kush mountains accompanied only by his family and two hundred fighting men, he conquered the city of Kabul in Afghanistan. In 1526, using tactics he had learned from the Persians, with whom he had allied in the past, including the use of artillery, Babur defeated the much larger army of the Delhi Sultanate, a Muslim state in northern India, and established the Mughal (the Persian pronunciation of Mongol) Empire. `, name: 'history1.1', rows: 5},
          {prompt: `Despite his desire to become ruler of India and his fascination with his new land, Babur did not adopt Indian culture. Although he was intrigued by the subcontinent&apos;s animals, plants, and climate, he had little interest in its people or in the Hindu religion. He described the people of India as lacking both personal beauty and manners. He admired the land&apos;s wealth but strove to re-create for himself and his family a taste of his homeland by designing gardens in the Persian style. He remained firmly oriented toward central Asia and maintained a post road and waystations connecting the Mughal capital of Agra to Kabul. When he died, he was interred at Agra, but to honor his wishes, his body was later taken home to Kabul for burial.`, name: 'history1.2', rows: 5},
          {prompt: `When Babur died in 1530, his eldest son Humayun inherited Mughal India. Humayun&apos;s reign was not a successful one. After only ten years, he was forced to flee after being defeated in battle by Sher Shah Suri, the ruler of the Indian state of Bihar. Humayun sought refuge at the court of the Safavid Shah Tahmasp in Persia, where he became deeply immersed in Persian culture. In 1555, he returned to India and won back his throne, but his victory was short-lived. Only a few months after retaking the Indian city of Delhi, Humayun died after tripping on a steep staircase. `, name: 'history1.3', rows: 5},
      {prompt: `Humayun&apos;s fourteen-year-old son Akbar inherited the throne. Although he was illiterate, possibly because of severe dyslexia, Akbar became the greatest of the Mughal emperors. Unlike his father and grandfather, who had remained oriented toward central Asia, Akbar embraced India. He actively sought to incorporate Indians, both Muslim and Hindu, into his kingdom. Although he was aggressive militarily and expanded the bounds of the Mughal Empire across the northern part of the subcontinent and into the central plains to the south, he allowed local rulers to retain control of their lands so long as they submitted to him.`, name: 'history1.4', rows: 5}
    ]
  }

  const greece_text = {
    type: jsPsychSummarizeText,
    preamble: `Ancient Greece`,
    questions: [
      {prompt: `The territory of Greece is mountainous; as a result, ancient Greece consisted of many smaller regions, each with its own dialect, cultural peculiarities, and identity. Regionalism and regional conflicts were a prominent feature of ancient Greece. Cities tended to be located in valleys between mountains or on coastal plains and dominated the countryside around them. Without a powerful, centralized state, smaller governing bodies created political order. One such type of governing body was the city-state or polis. Initially, the term polis referred to a fortified area or citadel which offered protection during times of war. Because of the relative safety these structures afforded, people flocked to them and set up communities and commercial centers. Over time, poleis—the plural of polis—became urban centers whose power and influence extended to the surrounding agricultural regions, which provided resources and paid taxes.`, name: 'history2.1', rows: 5},
      {prompt: `Some of the most important city-states were Athens, Sparta, Thebes, Corinth, and Delphi. Located in a fertile area of the Peloponnesus, a peninsula in southern Greece, Sparta&apos;s population steadily grew between 800 and 600 BCE. As Sparta developed a complex and strong economy, it extended its power throughout the Peloponnesus and brought the people of neighboring villages under its control. The people in these villages, however, were not accorded equal status with Spartans. Instead, they became helots: a class of unfree laborers who, rather than being owned privately, were subjects of the Spartan state. They were able to have families and exercised some degree of freedom, but they were tied to the land and were required to supply Sparta with food.`, name: 'history2.2', rows: 5},
      {prompt: `Spartans expended vast resources to develop a powerful and structured military apparatus to prevent and subdue rebellions. Though there was a very sharp distinction between Spartans and helots, Spartan society itself did not have a complex social hierarchy, at least in theory. Instead of wealth being a distinguishing marker, social status was determined by military achievements. Strength and discipline were emphasized, even in children at a very young age. At age seven, Spartan boys were separated from their families and sent to live in military barracks, where they underwent serious military training, leading up to active service when they were barely out of their teens.`, name: 'history2.3', rows: 5},
      {prompt: `Like all Greek societies, Sparta was dominated by male citizens, and the most powerful of these came from a select group of families. The Spartan political system was unusual in that it had two hereditary kings from two separate families. These monarchs were particularly powerful when one of them led the army on campaign.`, name: 'history2.4', rows: 5},
      {prompt: `Women in Sparta had more rights than women in other Greek city-states. In Sparta, they could own property, which they often gained through dowries and inheritances. Some women became rich when the men in their families were killed in war. In fact, women eventually controlled nearly half of Spartan land. In addition, Spartan women could move around with reasonable freedom, wear non-constricting clothing, enjoy athletics, and even drink wine.`, name: 'history2.5', rows: 5}
    ]
  }

  const ghana_text = {
    type: jsPsychSummarizeText,
    preamble: `The Ghana Empire`,
    questions: [
      {prompt: `While there were many city-states and small kingdoms in West Africa for centuries, the Ghana Empire was the first major agrarian empire to arise in the region. Its history is shrouded in mystery. While they had a complex society, a division of labor, wealth, and trade, the Ghana Empire (like the Inca in the Americas) did not have a form of writing as we know it. As such, much of the information we have of the civilization depends on oral histories and the medieval writings of Arab traders. The story goes that a man named Kaya Magar Ciss&eacute;, king of a realm called Wagadou, rose to prominence in West Africa around 300 CE. The sons and grandsons of his house then extended their rule over several other kingdoms, turning them into vassal states. Many of the names of the Ghana rulers are unknown and only a few of their deeds have passed into recorded history.`, name: 'history3.1', rows: 5},
      {prompt: `What we do know is, around 300 CE, West Africans domesticated the camel. That species has a distinct advantage in the desert, and this revolutionized trade across the Sahara. Rapidly growing trade brought a lot of wealth and power to West Africa, just as the Ghana Empire was getting its start.`, name: 'history3.2', rows: 5},
      {prompt: `The Ghana Empire, in particular, grew rich from the trans-Sahara trade. It certainly helped that the empire had control over the three major gold fields to the south of them. As such, Ghana was referred to by traders as “the Land of Gold,” and the kings of Ghana were sometimes called “the Lords of the Gold.” As a result, the empire flourished. The king of Ghana had a monopoly on all gold nuggets that were found in the mines. The people were allowed to trade in gold dust, but had to turn over any gold nuggets to the government. As such, the state became very powerful as well, adding to the complexity of Ghana&apos;s agrarian civilization.`, name: 'history3.3', rows: 5},
      {prompt: `Once the Arabs moved into Egypt and Northwest Africa in the 600s and 700s CE, trade intensified and Ghana grew even richer. The West Africans became major traders in the Old World. They sold ivory, salt, iron tools and weapons, furniture, textiles, sandals, herbs, spices, fish, rice, honey, and kola nuts. This is also the point in history when the large exportation of slave labor from West Africa to the Islamic world began. Centuries later, with the arrival of the Portuguese, a similar exportation of African people as slave labor would kick off the massive coerced exodus of Africans to the Americas, in which millions died in the appalling conditions of the crossing, and millions more led a life of subjugation and cruelty once they arrived. Slavery is a negative characteristic of many early agrarian civilizations, from Mesopotamia, to Egypt, to the Greco-Romans, but in the long run it was to prove particularly devastating to the populations of West Africa, after about 1500 CE.`, name: 'history3.4', rows: 5},
      {prompt: `It was the monopoly on West African gold, however, that allowed the Ghana Empire to reach the height of its power, at a time when Europe was undergoing decline after the fall of the Roman Empire. Ghana&apos;s rule extended as far as the Niger valley. The city of Koumbi Saleh, thought by many archaeologists to be the empire&apos;s capital, is estimated to have supported 15,000 to 20,000 people. This may not seem like much compared to other ancient cities. However, this was an astounding feat for a city in the Sahel, where the climate was dry and drinking water was scarce. The town had many wells to support its populace, and also to irrigate plants that were grown within the city. The fact that 15,000 to 20,000 people were able to live in a city so close to the harsh Sahara is an astounding feat of architecture and engineering. Koumbi Saleh also boasted an impressive palace complex with a number of ornate buildings to house the many nobles, officials, and the king.`, name: 'history3.5', rows: 5},
      {prompt: `The ruler of the Ghana Empire is also said to have sent many opulent gifts to his neighbors. This was easily done, considering the immense amounts of gold he possessed. Also, Arab sources tell us that in the 1000s, the Ghana Empire could field 200,000 soldiers in the field, of whom 40,000 were archers. The number is almost certainly exaggerated, as medieval writers are known to do, but the point is that the empire&apos;s military force was considerable and enough to give Arab visitors cause for amazement. All seems to indicate that thanks to agriculture, mining, and trade, Ghana was a wealthy and powerful civilization in Africa. Its society was to dominate the region for centuries. It was West Africa&apos;s first major power, and was not the last.`, name: 'history3.6', rows: 5}
    ]
  }

  const blood_cells_text = {
    type: jsPsychSummarizeText,
    preamble: `Red Blood Cells`,
    questions: [
      {prompt: `Red blood cells have the vital role of carrying oxygen to all of the cells in the body. They also pick up waste carbon dioxide for removal. These cells are the most numerous of the blood cells. The disk shape of red blood cells results in a large surface area, which enables them to be efficient at gas diffusion.`, name: 'science1.1', rows: 5},
      {prompt: `Red blood cells contain a large, complex protein called hemoglobin. Hemoglobin binds to the oxygen and carbon dioxide that the red blood cells transport. Each red blood cell contains about 250 million hemoglobin molecules, each carrying four molecules of oxygen. Hemoglobin also contains iron, which gives blood its red color. Molecular oxygen can also be transported by another route, dissolved in blood plasma. However, oxygen is poorly soluble in water, so only about 1.5% is carried in dissolved form. Therefore, most oxygen is carried by hemoglobin.`, name: 'science1.2', rows: 5},
      {prompt: `Red blood cells lack a nucleus and the organelles found in other cells. Therefore, these cells cannot reproduce or repair themselves. Red blood cells live for about three or four months before being broken down in the spleen. Iron from the broken-down cells is returned to the bone marrow to be recycled into new hemoglobin.`, name: 'science1.3', rows: 5},
      {prompt: `Sometimes blood does not transport enough oxygen, resulting in a condition called anemia. This makes a person feel tired and weak. Anemia can result from too little iron in the diet, loss of blood due to injury or menstruation, or various medical conditions. One type of anemia, called sickle-cell disease, is characterized by red blood cells that are sickle-shaped instead of disk-shaped. The shape of the cells causes them to clog blood vessels, preventing oxygen from reaching muscles and other tissues.`, name: 'science1.4', rows: 5}
    ]
  }

  const blood_pressure_text = {
    type: jsPsychSummarizeText,
    preamble: `Blood Pressure`,
    questions: [
      {prompt: `Blood pressure is the pressure exerted by blood on the walls of a blood vessel that helps to push blood through the body. Systolic blood pressure measures the amount of pressure on vessels while the heart is beating. Diastolic blood pressure measures the pressure in the vessels between heartbeats. Many factors can affect blood pressure, such as hormones, stress, exercise, eating, sitting, and standing. Blood flow is regulated by the size of blood vessels, by the action of smooth muscle, and by fluid pressure.`, name: 'science2.1', rows: 5},
      {prompt: `The pressure of the blood flow is produced by the pressure of the fluid against the walls of the blood vessels. Fluid will move from areas of high to low pressures. In the arteries, the pressure near the heart is very high and blood flows to the arterioles. During systole, when new blood is entering the arteries, their walls stretch to accommodate the increase of pressure; during diastole, they return to normal because of their elastic properties.`, name: 'science2.2', rows: 5},
      {prompt: `Cardiac output is the volume of blood pumped by the heart in one minute. It is calculated by multiplying the number of heart contractions that occur per minute times the stroke volume. Therefore, cardiac output can be increased by increasing heart rate. However, cardiac output can also be increased by increasing stroke volume.`, name: 'science2.3', rows: 5},
      {prompt: `During heavy exertion, the blood vessels relax and increase in diameter, offsetting the increased heart rate and ensuring adequate blood gets to the muscles. Stress can also trigger the release of hormones, which can cause a decrease in the diameter of the blood vessels. A decrease in the diameter of blood vessels increases blood pressure. Even standing up or lying down can have a great effect on blood pressure.`, name: 'science2.4', rows: 5}
    ]
  }

  const kidneys_text = {
    type: jsPsychSummarizeText,
    preamble: `The Kidneys`,
    questions: [
      {prompt: `The kidneys are a pair of bean-shaped organs just above the waist. They have many functions in the body, including producing hormones, absorbing minerals, and filtering blood and producing urine.`, name: 'science3.1', rows: 5},
      {prompt: `Urine is the liquid waste product of the body. Wastes in the blood come from the normal breakdown of tissues, such as muscles, and from food. After the body has taken the nutrients it needs from food, some of the wastes are absorbed into the blood. If the kidneys did not remove them, they would build up in the blood and damage the body. The actual removal of wastes from the blood occurs in tiny units inside the kidneys called nephrons.`, name: 'science3.2', rows: 5},
      {prompt: `The kidneys secrete hormones that help maintain homeostasis. Erythropoietin is a hormone that stimulates bone marrow to produce red blood cells when more are needed. They also secrete the hormone renin, which regulates blood pressure, and calcitriol, the active form of vitamin D, which helps maintain calcium for bones. The kidneys themselves are also regulated by hormones. Antidiuretic hormone from the hypothalamus stimulates the kidneys to produce more concentrated urine when the body is low on water.`, name: 'science3.3', rows: 5},
      {prompt: `The kidneys are involved in maintaining the water level in the body, and regulating red blood cell levels and blood pressure. They react to changes in the body&apos;s water level throughout the day. As water intake decreases, the kidneys adjust accordingly and leave water in the body instead of helping remove it through the urine. The kidneys need constant pressure to filter the blood. When the blood pressure drops too low, the kidneys increase the pressure by producing angiotensin, a blood vessel-constricting protein.`, name: 'science3.4', rows: 5}
    ]
  }

  const clothes_text = {
    type: jsPsychSummarizeText,
    preamble: `King's Clothes`,
    questions: [
      {prompt: `Many years ago, there lived in Gibraltar a young fellow named Guifa. People said Guifa was so silly that he wasn't sure of the weather when it was raining in buckets. But he was a nice, sensitive lad and he wanted to have friends. Guifa never had much use for fine airs and stuffy clothes. He wore rags for clothes and never wore any shoes. Doors were closed in his face, and sometimes people wouldn't even talk to him. He was never asked to a wedding or a feast. Life was none too pleasant for Guifa. His mother thought, "Our neighbors seem like good people. Perhaps they will make friends with my son."`, name: 'folk1.1', rows: 5},
      {prompt: `One day, she sent him to take some bread to the neighboring farm. The loaves were warm and gave off a delicious smell. Guifa went off whistling and kicking stones in the road. He followed the lane that twisted and turned through the fields. Soon he came to the farmhouse. "Hello," said Guifa, "my mother sent you this." He held out a basket containing the loaves of bread. The farmer was standing at the gate. He looked at Guifa's ragged clothes and at his feet, which had gotten all dusty. "Drop it there and get out of here, you scarecrow," the farmer cried. Guifa set the basket of bread next to the gate. Then he turned sadly for home. When he reached his cottage, he told his mother what had happened. "Just because I don't wear fine clothes, they treated me like a dog," he said. Guifa's mother worried about this.`, name: 'folktale1.2', rows: 5},
      {prompt: `A few weeks later, she sent her son to take a calf to the same farm. She did not want the boy to be put to shame again. So, she dressed him in a fine white shirt, good breeches, a nice blue coat, and good shoes. Guifa looked like a different fellow. He almost wouldn't have recognized himself. Off he went, whistling gaily. When he came to the farm, both the farmer and his wife were standing at the gate. Neither of them recognized Guifa. "I have brought you a calf," Guifa said. They thanked him and invited him into the farmhouse. There they served him a delicious meal. Guifa had a wonderful time joking and eating the bread and cheese and vegetables. After the meal, the farmer sat back in his chair. The farmer's wife began to wash the dishes. The farmer asked the boy to tell him about this and that.`, name: 'folktale1.3', rows: 5},
      {prompt: `But instead, Guifa stood up. He stuffed some of the bread and cheese in the pockets of his coat, and he put some of the vegetables into his hat. The farmer didn't understand what was going on and puffed nervously on his pipe. Guifa bowed low and looked at his bulging pockets. Then he said, "Here is food for you, my good clothes and fine hat. I want to thank you, my good clothes and fine hat, because it is you who were treated like a king today. Because of you, my good clothes and fine hat, I had a delicious meal. When I came here the last time without you, I was treated like a crazy dog." Then he turned and walked out of the farmhouse, leaving the farmer and his wife with their mouths hanging open. After that, people no longer called Guifa stupid or slow. Soon he had many friends who didn't mind that he still preferred to wear rags and no shoes.`, name: 'folktale1.4', rows: 5}
    ]
  }

  const feast_text = {
    type: jsPsychSummarizeText,
    preamble: `The Feast on the Mountain`,
    questions: [
      {prompt: `It was Spider's birthday. He planned a huge party with food and cakes and sweets of all kinds. Spider sent party invitations to all the animals to come eat with him, and Tortoise came, too. Tortoise didn't like to dance and run about the forest. Spider thought Tortoise was a nuisance and decided to be mean to him. So Spider told all the animals that they had to wash their dirty hands before eating. All of the animals went to do as Spider had said. There was a path that went through the forest. Tortoise went to the stream and washed. But he had a problem after that. As he walked back, his hands got dirty again. Tortoise tried over and over, but he couldn't walk any other way. So he never got to eat at Spider's table.`, name: 'folktale2.1', rows: 5},
      {prompt: `Tortoise decided to get even with Spider. He decided that he would have an even bigger feast than the one that Spider had had for his birthday. Tortoise sent a call to all of the animals to come to a banquet. He knew that Spider would come, of course. When the guests arrived, Tortoise told them that the feast would be in his house under the water. He knew that Spider was too light to swim down to where they were eating. But Spider borrowed a coat and filled the pockets with stones. They made him heavy enough to swim to Tortoise's feast. The banquet table stood in the middle of the dining room in Tortoise's house. The table was covered with wonderful things to eat. There were also red wines and white wines and pink wines. Tortoise saw the stones in Spider&apos;s pockets. "I won't let him get the better of me this time," Tortoise thought. Tortoise told his guests, "You may not wear your coats at the table."`, name: 'folktale2.2', rows: 5},
      {prompt: `Spider was troubled by this and didn't want to take off his coat. He shuffled his feet and looked all around. He thought, "If I take off my coat, I'll float to the top again. The stones that are in my pockets are what hold me down." So Spider just ignored what Tortoise said. Spider hoped that nobody would notice what he did. But when he tried to sit at the table, Tortoise stopped him. Tortoise said, "When you gave your feast you did as you liked. When I give mine, I can do what I like. You must do what I say." So Spider took his coat off. No sooner had he done so than he rose to the surface of the water. Tortoise laughed and laughed. "Now we are even," he called. But as for Spider, he did not get any food that day.`, name: 'folktale2.3', rows: 5}
    ]
  }

  const anansi_text = {
    type: jsPsychSummarizeText,
    preamble: `Why They Name the Stories for Anansi`,
    questions: [
      {prompt: `Once upon a time, Ant decided children should treat him with more respect. So he went to Master King and told him so. Master King said, "Well, Blacksnake is a very wise and clever creature. If you trick him and bring him back stretched on a pole, then I will tell the children to respect you." Ant knew that it is really hard to catch a snake. He also knew that Blacksnake loved to take walks and eat animals. So he got a big bear trap. He set it in the middle of the path that Blacksnake took for his daily walks. He opened the jaws of the trap. Then he covered the trap with lots of grass. When he was finished, you couldn't see the trap at all. Ant thought, "When Mr. Blacksnake comes along, he won't even see the trap. He'll slither over the grasses and the trap will snap him. Then I will have caught him!"`, name: 'folktale3.1', rows: 5},
      {prompt: `Soon, Blacksnake came slithering along the path on his morning walk. But he was very clever and saw the trap immediately. So, when he got to it, he just arched his body above the jaws of the trap. Then he flipped his tail across and went on down the path. Ant thought, "I need to use a different kind of trap." So he dug a pit in the middle of another path. Ant made the pit very, very wide. He made the sides of the pit very smooth and straight so the snake couldn't climb out of it. The weather was warm and pretty. Ant hummed a song as he covered the opening of the pit with sticks. "I'll bait this pit with a sheep," Ant decided. "Blacksnake will be so hungry that he won&apos;t notice the trap." Now, Mr. Blacksnake had very large eyes. He also had good eyesight, and he saw this trap, too. He just walked around the edge of the pit and took the sheep.`, name: 'folktale3.2', rows: 5},
      {prompt: `Later on, he met Ant and said, "You've been setting traps for me everywhere. You will never catch me, because I am wiser and more clever than you or any other creature." Ant said, "Well, Mr. Blacksnake, I must tell you the truth. I heard the creatures talking up at Master King's palace. They all said that Mr. Yellowtail Snake was the longest snake in the forest. I told them that you were much longer, but they just laughed. Then Ant said, "I bet my money on your length." "I risked everything that I won in last month's lottery," Ant told him. "Please help me prove to Master King that you are longer than Mr. Yellowtail." Now Blacksnake was proud of his length and loved to brag about it. He said, "I am longer than Yellowtail." Ant said, "We must go to Master King together, or he won't believe it. Lie down and stretch out, and I'll take you to Master King that way."`, name: 'folktale3.3', rows: 5},
      {prompt: `Blacksnake didn't want anyone to think he wasn't the longest, especially the King. Blacksnake lay down and stretched himself out to his full length. When Blacksnake was stretched all the way out, Ant tied him to a pole quick and tight. Then he threw that pole over his shoulder and carried him to the king. "Well, Master King, I brought you Mr. Blacksnake tied up on a pole." The king replied, "You were able to trick the wisest and cleverest of all the creatures. Therefore, I will order all the children to respect you from now on." And so he did.`, name: 'folktale3.4', rows: 5}
    ]
  }